### ISSUE TITLE
BUG IN THE README FILE 

### ISSUE THREAD

**Issue by akrish4** [releax/appctl#8]
I found there is a bug in the readme file , the logo is not visible , kindly assign me it @r1walz

**Comment by r1walz** [comment]
@itsManjeet can you look into it?

**Comment by akrish4** [comment]
> @itsManjeet can you look into it?

Could u pls assign it to me , i=I will make it correct as I am participating in DWOC and SWOC aswell 
@r1walz  @itsManjeet

**Comment by ssg8288** [comment]
@akrish4 fyi this project have been removed from the dwoc as I talked to the core team after having pulled two PR's and issues got to know .... so close the issue the maintainer won't respond.

**Comment by itsManjeet** [comment]
@akrish4 @r1walz @ssg8288 
Sorry for the late response. Actually things are little bit messed and i'm engaged other issues.
Codes are migrated to [gitlab](https://gitlab.com/rlxos/softwares/appctl)
You can submit you issues and pull request here.

**Comment by ssg8288** [comment]
> 
> 
> I found there is a bug in the readme file , the logo is not visible , kindly assign me it @r1walz

if you are under dwoc then let me tell you this project has been removed from dwoc and contributing anything to it won't count for the leaderboard and all contributions has to be made on github only.
